name: Deploy Firebase Backend

on:
  push:
    branches:
      - main  # Spustí deploy při každém pushnutí do hlavní větve

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Verify files
        run: ls -la

      - name: Install dependencies in backend-functions
        run: cd backend-functions && npm install

      - name: Setup Google Service Account credentials
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json" >> $GITHUB_ENV

      - name: Deploy to Firebase
        run: firebase deploy --project kalendar-831f8
